# Only needs to contain packages required for packages referenced
#  by this repo, but adding more is fine


---
- hosts: localhost 
  become: yes
  tasks:
  - name: Install packages
    pacman:
      name:
      - vim
      - zsh
      - festival
      - tmux
      - git
      state: present
