---
- hosts: localhost 
  become: yes
  tasks:
  - name: Install base packages
    pacman:
      name:
      - vim
      - zsh
      - festival
      - tmux
      - jq
      - terraform
      - jdk-openjdk
      - maven
      state: present
