---
- hosts: localhost 
  vars:
    J_user: "{{ lookup('env','SUDO_USER') if lookup('env','USER') == 'root' else lookup('env','USER') }}"
  become: yes
  become_user: "{{J_user}}" # TODO : should be a var
  tasks:

  - name: "write vimrc file"
    template:
      src: ./templates/vim/vimrc.j2
      dest: ~/.vimrc

  - name: "write vimrc.clean file"
    template:
      src: ./templates/vim/vimrc.clean.j2
      dest: ~/.vimrc.clean
