DOT_DIR="${HOME}/.zsh"

# bins
BIN_PATH="${DOT_DIR}/bin"
#chmod +x ${BIN_PATH}/* # perms set by ansible

# Scripts
for file in ${SCRIPT_PATH}; do
    # TODO : only execute .sh$ files
    ./${file}
done

# TODO : Don't re-export PATH if already contained
export PATH="${PATH}:${BIN_PATH}"

# sources
SOURCE_PATH="${DOT_DIR}/source"
for file in ${SOURCE_PATH}/*; do
    . "${file}"
done
