DOT_DIR="${HOME}/.zsh"

# bins
# TODO : Don't re-export PATH if already contained
BIN_PATH="${DOT_DIR}/bin"
export PATH="${PATH}:${BIN_PATH}"

# sources
SOURCE_PATH="${DOT_DIR}/source"
for file in ${SOURCE_PATH}/*; do
    source "${file}"
done

# Scripts
# : ensure executes last, as depends on bin (and maybe source)
SCRIPT_PATH="${DOT_DIR}/scripts"
for file in ${SCRIPT_PATH}/*; do
    #echo ${file}
    # TODO : only execute .sh$ files
    ${file}
done
